[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_marketplace_v2 = "29hLYT9LFzKpf98UHqWU4zxm91tWfimkcPq7uNYcdVsR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tungleanh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
